# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_slug', models.SlugField()),
                ('bio', models.TextField()),
                ('mugshot', models.ImageField(height_field=200, upload_to='Users/lera_alfimova/ProjectTicoTeam1/engage/engage/uploads/', width_field=200)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=600, upload_to='Users/lera_alfimova/ProjectTicoTeam1/engage/engage/uploads/', width_field=800)),
                ('cutline', models.TextField()),
                ('credit', models.ManyToManyField(to='blog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.ManyToManyField(to='blog.Author')),
                ('images', models.ManyToManyField(to='blog.Image')),
            ],
        ),
    ]
